### ISSUE TITLE
 想请问下，你的hdmi可以输出吗，我的只有dp可以输出，hdmi始终没有输出

### ISSUE THREAD

**Issue by coder4lin** [STFQ/MSI-Z490-GAMING-PLUS-for-hackintosh#1]

**Comment by STFQ** [comment]
你的显示器是4k的吗？我这边的HDMI（主板上的HDMI接口）输出也是有问题的，需要在显卡注入那里加入参数才能正常输出

**Comment by STFQ** [comment]
我那个最新发布的版本，里面就是修复HDMI输出的，是可以正常输出的，你可以参考下那个。那个其实就是将DP的接口映射到HDMI上，但是这块主板的HDMI接口不是4K的，我自己最新的正式版本已经删除了相关的参数了，毕竟这个接口没法用4k 60hz相当于没用

**Comment by coder4lin** [comment]
> 我那个最新发布的版本，里面就是修复HDMI输出的，是可以正常输出的，你可以参考下那个。那个其实就是将DP的接口映射到HDMI上，但是这块主板的HDMI接口不是4K的，我自己最新的正式版本已经删除了相关的参数了，毕竟这个接口没法用4k 60hz相当于没用

好的，谢谢答复，感觉可能因为我显卡跟你注入id不一致，导致用了您的efi，hdmi还是没得输出。
